resources:
  - repo: self
queue:
  name: Hosted Linux Preview
  demands: npm

steps:
  - script: |
      npm install
    displayName: "npm install"
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip"
  - task: AzureRmWebAppDeployment@3
    displayName: "Function App Deploy: Super Simple Function App"
    inputs:
      azureSubscription: "8d3519e1-8089-4300-ab0b-bfeda0f9844c)"
      appType: functionapp
      WebAppName: "puppies-deanbryen"
      Package: "$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip"

